# Generated by Django 5.1.4 on 2026-01-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0027_bannerevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='leadership_pics/')),
                ('is_current', models.BooleanField(default=True)),
                ('region', models.CharField(blank=True, choices=[('north', 'North'), ('east', 'East'), ('west', 'West'), ('south', 'South'), ('central', 'Central')], max_length=20, null=True)),
            ],
        ),
    ]
