# Generated by Django 5.2.9 on 2026-01-02 09:08

import django.db.models.deletion
import spai_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0027_bannerevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=spai_app.models.renew_proof_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renew_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
