# Generated by automated patch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0028_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leadership',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True, choices=[('north', 'North'), ('east', 'East'), ('west', 'West'), ('south', 'South'), ('central', 'Central')]),
        ),
    ]
