# Generated by Django 5.1.4 on 2026-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0029_add_leadership_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(blank=True, default='Not Active', max_length=30, null=True),
        ),
    ]
